apiVersion: v1
kind: Service
metadata:
  name: fallout-service
  labels:
    app: fallout-deployment
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fallout-deployment
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fallout-deployment
spec:
  selector:
    matchLabels:
      app: fallout-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: fallout-deployment
    spec:
      containers:
      - name: master
        image: alanduarte/dockergamesfallout
        ports:
        - containerPort: 80